source 'https://rubygems.org'

gem 'bundler'
gem 'cocoapods'
gem 'github_changelog_generator', '>= 1.14.3'
gem 'jazzy'
gem 'jekyll', '>= 4.0.0'
gem 'rufo'
gem 'solargraph'
gem 'travis', '>= 1.8.10'
gem 'travis-conditions'
