#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT=$(pwd -P)

# set -e

echo ''
echo ''
echo 'Beginning dotfiles installation'

if ! [ -x "$(command -v brew)" ]; then
  echo 'Error: homebrew is not installed.' >&2
  exit 1
fi

brew bundle

git config --global color.ui true

echo ''
echo "Let's setup Git"

read -p 'Full Name: ' name

git config --global user.name $name

read -p 'Email: ' email

read test

git config --global user.email $email


# find the installers and run them iteratively
for installer in $(find . -name "*install.sh"); do
  echo ''
  echo "Running ${installer}"
  sh -c "${installer}"
done


echo ''
echo 'Completed dotfiles installation'
echo ''
echo ''
