#!/usr/bin/env bash
#
# Main Script

# --------------
# Imports
# --------------

. "scripts/globals.sh"

# --------------
# Functions
# --------------

main() {
  if [ "$(dirname "$DOTFILES_ROOT")" != "$HOME" ]; then
    echo "Must have .dotfiles/ installed in home directory"
    exit 1
  fi

  if [ "$(id -u)" == "0" ]; then
    echo "FAILURE: This script must not be run as root"
    exit 1
  fi

  if [ "$1" != "install" ] && [ "$1" != "update" ]; then
    echo "$1 is unsupported"
    exit 1
  fi

  set -e

  sudo chown -R "$(whoami)" /usr/local/lib /usr/local/sbin

  # find the installers and run them iteratively
  while IFS= read -r -d '' installer; do
    echo ''
    echo "Running ${installer}"
    sh "${installer}" "$1"
  done < <(find . -name "*install.sh" -print0)
}

# --------------
# Main Script
# --------------

main "$@"
