#!/usr/bin/env bash
#
# bootstrap installs things.

# --------------
# Functions
# --------------

main() {
  DOTFILES_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

  if [ "$(dirname "$DOTFILES_ROOT")" != "$HOME" ]; then
    echo "Must have .dotfiles/ installed in home directory"
    exit 1
  fi

  if [ "$(id -u)" == "0" ]; then
    echo "FAILURE: This script must not be run as root"
    exit 1
  fi

  case "$1" in
  "install") install ;;
  "update") update ;;
  *) echo "Unsupported" ;;
  esac
}

install() {
  set -e

  # find the installers and run them iteratively
  for installer in $(find . -name "*install.sh"); do
    echo ''
    echo "Running ${installer}"
    sh "${installer}" install
  done
}

update() {
  set -e

  # find the installers and run them iteratively
  for installer in $(find . -name "*install.sh"); do
    echo ''
    echo "Running ${installer}"
    sh "${installer}" update
  done
}

# --------------
# Main Script
# --------------

main "$@"
