#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT=$(pwd -P)

set -e

echo ''
echo ''
echo 'Beginning dotfiles installation'

if ! [ -x "$(command -v brew)" ]; then
  echo 'Error: homebrew is not installed.' >&2
  exit 1
fi

# find the installers and run them iteratively
for installer in $(find . -name "*install.sh"); do
  echo ''
  echo "Running ${installer}"
  sh -c "${installer}"
done

brew bundle

echo ''
echo 'Completed dotfiles installation'
echo ''
echo ''
