#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT=$(pwd -P)

set -e

echo ''
echo ''
echo 'Beginning dotfiles installation'

if [ "$(id -u)" == "0" ]; then
  echo "FAILURE: This script must not be run as root"
  exit 1
fi

# find the installers and run them iteratively
for installer in $(find . -name "*install.sh"); do
  echo ''
  echo "Running ${installer}"
  sh -c "${installer}"
done

echo ''
echo 'Setting up Homebrew'

if ! [ -x "$(command -v brew)" ]; then
  echo ''
  echo 'Installing Homebrew'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew upgrade
fi

brew bundle

if `gem list bundler -i`; then 
  echo "Bundler gem is installed!";
else
  gem install bundler
fi

bundle install --system

echo ''
echo 'Completed dotfiles installation'
echo ''
echo ''
